spring:
  application:
    name: supermercado
  server:
    error:
      include-message: always
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=supermercado;encrypt=true;trustServerCertificate=true
    username: sa
    password: ENC(dUEVIuG0Ih4teurLsPkbqvaXMJxFxFOqX1e121VXSN90xd/UgQSW/dpFVf7c5Pah)
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MYSQL5Dialect

springdoc:
  swagger-ui:
    url: /swagger.yaml